### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by titusjaka** [titusjaka/go-sample#4]
- [x] replace cli with kong
- [x] use uber/mock 
- [x] use pgx instead of pq
- [x] get rid of go-kit
- [ ] #27
- [ ] #28
- [x] get rid of embedded-postgres, use postgres instance instead
- [x] use slog instead of custom logger
- [x] use NotifyContext for graceful shutdown
- [x] enable all disabled linters
- [x] update documentation
- [x] enable CodeQL
- [x] fix code coverage step
- [x] release v2
